# Generated by Django 2.2.1 on 2021-12-17 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('cod_dane', models.IntegerField(blank=True, default=0, null=True, verbose_name='COD-DANE')),
                ('nombre_ciudad', models.CharField(default='', max_length=100, verbose_name='Nombre del municipio/ciudad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre_ciudad'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('nombre_pais', models.CharField(default='', max_length=100, verbose_name='Nombre del Pais')),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'ordering': ['nombre_pais'],
            },
        ),
        migrations.CreateModel(
            name='Terceros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('nit', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='NIT/CC')),
                ('tipo_nit', models.IntegerField(blank=True, choices=[(11, 'REGISTRO CIVIL'), (12, 'TARJETA DE IDENTIDAD'), (13, 'CEDULA DE CIUDADANIA'), (21, 'TARJETA DE EXTRANJERIA'), (22, 'CEDULA DE EXTRANJERIA'), (31, 'NIT'), (41, 'PASAPORTE'), (42, 'TIPO DE DOCUMENTO DE EXTRANJERIA')], default=31, null=True)),
                ('dv_nit', models.CharField(blank=True, default=0, max_length=1, null=True, verbose_name='Digito de Verificacion')),
                ('tipo_entidad', models.IntegerField(blank=True, choices=[(1, 'REGIMEN SIMPLIFICADO'), (2, 'REGIMEN COMUN')], default=2, null=True)),
                ('nombre1', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Primer nombre')),
                ('nombre2', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Segundo nombre')),
                ('apellido1', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Primer apellido')),
                ('apellido2', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Segundo apellido')),
                ('rzn_social', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Razón Social')),
                ('tel1', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Teléfono fijo #1')),
                ('tel2', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Teléfono fijo #2')),
                ('celular', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Número de celular')),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Código postal')),
                ('direccion', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, default='', max_length=200, null=True, verbose_name='E-Mail')),
                ('home_page', models.URLField(blank=True, default='', max_length=100, null=True, verbose_name='Pagina WEB')),
                ('ret_fuente', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='RETEFUENTE %')),
                ('ret_ica', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='RETEICA')),
                ('ret_iva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='RETEIVA')),
                ('porc_iva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='PORCENTAJE IVA')),
                ('cta_banco', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Cuenta Bancaria')),
                ('banco', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Nombre Banco Cuenta')),
                ('dias_credito', models.IntegerField(blank=True, default=0, null=True)),
                ('ciudad', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='generales.Ciudad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Terceros',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(default='', upload_to='fotos/', verbose_name='Archivo con Foto del Usuario')),
                ('logo', models.FileField(default='', upload_to='fotos/', verbose_name='Logo del Usuario')),
                ('nit', models.CharField(default='', max_length=30, verbose_name='NIT / CC #')),
                ('empresa', models.CharField(default='', max_length=100, verbose_name='Empresa')),
                ('direccion', models.CharField(default='', max_length=100, verbose_name='Direccion Comercial')),
                ('telefono', models.CharField(default='', max_length=100, verbose_name='Telefono Comercial')),
                ('email', models.CharField(default='', max_length=100, verbose_name='Telefono Comercial')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('cod_dane', models.CharField(default='', max_length=15, verbose_name='Codigo DANE del Departamento')),
                ('nombre_departamento', models.CharField(default='', max_length=100)),
                ('pais', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generales.Pais')),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.Departamento'),
        ),
    ]
