# Generated by Django 2.2.1 on 2021-03-16 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(default='', upload_to='fotos/', verbose_name='Archivo con Foto del Usuario')),
                ('nit', models.CharField(default='', max_length=30, verbose_name='NIT / CC #')),
                ('empresa', models.CharField(default='', max_length=100, verbose_name='Empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
