# Generated by Django 2.2.1 on 2021-11-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0003_terceros_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='db_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre DataBase'),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_db',
            field=models.CharField(default='', max_length=100, verbose_name='Usuario DataBase'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_db',
            field=models.CharField(default='', max_length=100, verbose_name='Usuario DataBase'),
        ),
    ]
