# Generated by Django 2.2.1 on 2021-12-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0004_auto_20211123_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password_db',
            field=models.CharField(default='', max_length=100, verbose_name='Password DataBase'),
        ),
    ]
