# Generated by Django 2.2.1 on 2021-12-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0005_auto_20211206_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='dias_credito',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='porc_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='PORCENTAJE IVA'),
        ),
    ]
