# Generated by Django 2.2.1 on 2022-03-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0006_profile_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vales',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='CONSECUTIVO VALES'),
        ),
    ]
