# Generated by Django 2.2.1 on 2021-12-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0006_auto_20211206_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password_db',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_db',
        ),
        migrations.AddField(
            model_name='profile',
            name='direccion',
            field=models.CharField(default='', max_length=100, verbose_name='Direccion Comercial'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='Telefono Comercial'),
        ),
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.FileField(default='', upload_to='fotos/', verbose_name='Logo del Usuario'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(default='', max_length=100, verbose_name='Telefono Comercial'),
        ),
    ]
