# Generated by Django 2.2.1 on 2022-03-18 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0007_profile_vales'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tercero_mostrador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generales.Terceros'),
            preserve_default=False,
        ),
    ]
