# Generated by Django 2.2.1 on 2021-12-17 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 19, 44, 24, 558533), verbose_name='Fecha documento'),
        ),
    ]
