# Generated by Django 2.2.1 on 2021-06-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='toal_copas',
            new_name='total_copas',
        ),
    ]
