# Generated by Django 2.2.1 on 2022-02-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='entrada',
            field=models.IntegerField(default=0, verbose_name='CONSECUTIVO ENTRADAS DE ALMACEN'),
        ),
    ]
