# Generated by Django 2.2.1 on 2022-02-10 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_movimientos_entrada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='entrada',
            new_name='documento_no',
        ),
    ]
