# Generated by Django 2.2.1 on 2021-06-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_auto_20210601_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_de_barra',
            field=models.CharField(blank=True, default='', help_text='Código de Barra', max_length=100, null=True),
        ),
    ]
