# Generated by Django 2.2.1 on 2021-06-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_auto_20210601_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='lote',
        ),
    ]
