# Generated by Django 2.2.1 on 2022-02-10 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_formulacion_formulacion1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulacion',
            name='producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalogos.Producto'),
        ),
    ]
