# Generated by Django 2.2.1 on 2021-12-08 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_auto_20211206_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos_detalle',
            name='codigo_de_barra',
            field=models.CharField(blank=True, default='', help_text='Código de Barra', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 21, 8, 12, 63222), verbose_name='Fecha documento'),
        ),
    ]
