# Generated by Django 2.2.1 on 2022-02-14 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0007_auto_20220210_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='tipo_movimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogos.Tipos_movimientos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipos_movimientos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='tipo',
            field=models.IntegerField(default=19),
        ),
    ]
