# Generated by Django 2.2.1 on 2021-12-09 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_auto_20211207_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos_detalle',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 15, 0, 52, 484700), verbose_name='Fecha documento'),
        ),
    ]
