# Generated by Django 2.2.1 on 2021-12-09 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_auto_20211209_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos_detalle',
            name='precio_venta',
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 15, 2, 1, 427242), verbose_name='Fecha documento'),
        ),
    ]
