# Generated by Django 2.2.1 on 2021-12-12 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_auto_20211209_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos_detalle',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 18, 31, 28, 119020), verbose_name='Fecha documento'),
        ),
    ]
