# Generated by Django 2.2.1 on 2022-02-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_auto_20220214_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, default='', help_text='Descripción del producto', max_length=100, null=True),
        ),
    ]
