# Generated by Django 2.2.1 on 2021-12-13 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_auto_20211212_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos_detalle',
            old_name='costo',
            new_name='costo_unidad',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='valor_documento',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='Valor documento'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 17, 55, 19, 240340), verbose_name='Fecha documento'),
        ),
    ]
