# Generated by Django 2.2.1 on 2021-12-13 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_auto_20211213_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos_detalle',
            old_name='costo_unidad',
            new_name='valor_unidad',
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 18, 4, 40, 597747), verbose_name='Fecha documento'),
        ),
    ]
