# Generated by Django 2.2.1 on 2022-02-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_auto_20220217_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(default=1, help_text='Talla', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_de_barra',
            field=models.CharField(blank=True, default='', help_text='Código de Barra', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('codigo_de_barra', 'talla')},
        ),
    ]
