# Generated by Django 2.2.1 on 2021-12-13 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0012_auto_20211213_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 18, 6, 43, 45228), verbose_name='Fecha documento'),
        ),
        migrations.AlterField(
            model_name='movimientos_detalle',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='Total'),
        ),
    ]
