# Generated by Django 2.2.1 on 2022-02-17 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0012_auto_20220217_1717'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('codigo_de_barra',)},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talla',
        ),
    ]
