# Generated by Django 2.2.1 on 2021-12-13 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0013_auto_20211213_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos_detalle',
            old_name='valor_unidad',
            new_name='costo',
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 18, 12, 43, 323957), verbose_name='Fecha documento'),
        ),
    ]
