# Generated by Django 2.2.1 on 2021-12-14 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0014_auto_20211213_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos_detalle',
            name='producto',
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 18, 27, 2, 122935), verbose_name='Fecha documento'),
        ),
    ]
