# Generated by Django 2.2.1 on 2021-12-14 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0015_auto_20211214_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos_detalle',
            name='producto',
            field=models.CharField(blank=True, default='', help_text='Nombre del producto', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 18, 28, 30, 914831), verbose_name='Fecha documento'),
        ),
    ]
