# Generated by Django 2.2.1 on 2021-12-14 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_auto_20211214_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 18, 38, 58, 931308), verbose_name='Fecha documento'),
        ),
    ]
