# Generated by Django 2.2.1 on 2021-12-17 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactDian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('modes', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mode')),
                ('tascode', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tascode')),
                ('intid', models.CharField(blank=True, max_length=20, null=True, verbose_name='IntID')),
                ('process', models.CharField(blank=True, max_length=3, null=True, verbose_name='Process')),
                ('retries', models.CharField(blank=True, max_length=2, null=True, verbose_name='retries')),
                ('cufe', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cufe')),
                ('url', models.URLField(blank=True, default='', max_length=1000, null=True, verbose_name='url para decarga el documento ')),
                ('pdf', models.URLField(blank=True, default='', max_length=1000, null=True, verbose_name='url para decarga del pdf')),
                ('attached', models.URLField(blank=True, default='', max_length=1000, null=True, verbose_name='url para decarga del xml del documento enviado al cliente')),
                ('pdf_file', models.FileField(blank=True, default='', null=True, upload_to='facturas/pdf')),
                ('xlm_file', models.FileField(blank=True, default='', null=True, upload_to='facturas/xml')),
            ],
            options={
                'verbose_name': 'Documento DIAN Factura',
                'verbose_name_plural': 'Documentos DIAN Facturas',
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('fecha_factura', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encabezado de Factura',
                'verbose_name_plural': 'Encabezados de Facturas',
            },
        ),
        migrations.CreateModel(
            name='NotasCredito',
            fields=[
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('no_nota', models.CharField(default='', max_length=40, primary_key=True, serialize=False, verbose_name='Numero de Documento')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('rangekey', models.CharField(blank=True, max_length=100, null=True, verbose_name='rangeKey')),
                ('issuedate', models.DateField()),
                ('issuetime', models.TimeField()),
                ('discrepancycode', models.IntegerField(choices=[(1, 'Devolucion parcial de bienes y/o no aceptacion parcial del servicio'), (2, 'Anulacion de factura electronica'), (3, 'Rebaja o descuento parcial o total'), (4, 'Ajuste de precio'), (5, 'Otros')], default=1)),
                ('note1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Note1')),
                ('note2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Note2')),
                ('note3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note3')),
                ('note4', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note4')),
                ('emailstyle', models.IntegerField(choices=[(0, 'Enlace de descarga (Por omision)'), (1, 'Como archivos adjuntos'), (2, 'Archivos adjuntos y Asunto homologado DIAN'), (99, 'No se envia correo')], default=1)),
                ('totalamount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total Nota')),
                ('discountamount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total descuentos Realizados')),
                ('extraamount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total de Cargos Adicionales Cobrados')),
                ('taxamount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total de Impuestos Cobrados')),
                ('prepaidamount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total de Pagos Anticipados')),
                ('payamount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total a Pagar')),
                ('whTaxAmount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total de Retenciones Aplicadas (whTaxes)')),
                ('anulado', models.BooleanField(blank=True, default=False, null=True)),
                ('factura', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='facturas.FactDian')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota credito',
                'verbose_name_plural': 'Notas Credito',
            },
        ),
        migrations.CreateModel(
            name='NotasCredito1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_unidad', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('precio_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('standard', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('cargos_o_descuentos', models.BooleanField(blank=True, default=False, null=True)),
                ('codigo_dian_cargo_descuento', models.CharField(blank=True, choices=[('00', 'Descuento por impuesto asumido'), ('01', 'Pague uno lleve otro'), ('02', 'Descuentos contractuales'), ('03', 'Descuento por pronto pago'), ('04', 'Envío gratis'), ('05', 'Descuentos especificos por inventarios'), ('06', 'Descuento por monto de compras'), ('07', 'Descuento de temporada'), ('08', 'Descuento por acturalizacion de productos / servicios'), ('09', 'Descuento general'), ('10', 'Descuento por volumen'), ('11', 'Otro descuento')], max_length=2, null=True)),
                ('descripcion_cargo_descuento', models.CharField(blank=True, max_length=100, null=True)),
                ('base_cargo_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_cargo_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('porcentaje_cargo_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('id_tax', models.CharField(blank=True, choices=[('01', 'IVA'), ('02', 'ICA'), ('03', 'Consumo'), ('04', 'Bolsas'), ('22', 'Descuentos especificos por inventarios')], max_length=2, null=True)),
                ('valor_total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('porcentaje_tax', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('valor_unidad_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('no_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.NotasCredito')),
            ],
            options={
                'verbose_name': 'Nota Credito Detalle',
                'verbose_name_plural': 'Notas Credito Detalles',
            },
        ),
        migrations.CreateModel(
            name='HookDian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('tascode', models.CharField(blank=True, max_length=200, null=True, verbose_name='TasCode')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Text')),
                ('alert', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Alert')),
                ('process', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Process')),
                ('process_change', models.BooleanField(blank=True, default=False, null=True)),
                ('process_newvalue', models.IntegerField(blank=True, choices=[(0, 'En Cola'), (1, 'En Proceso DIAN'), (2, 'Aceptado DIAN'), (90, 'Rechazado DIAN')], default=0, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True, verbose_name='eMail')),
                ('email_evento', models.CharField(blank=True, max_length=1000, null=True, verbose_name='eMail del evento')),
                ('email_status', models.IntegerField(blank=True, choices=[(0, 'Correo Enviado'), (1, 'Correo Recibido'), (2, 'Correo Rechazado'), (98, 'En Lista Negra')], default=0, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Facturas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta APP Factura',
                'verbose_name_plural': 'Respuestas API Facturas',
            },
        ),
        migrations.CreateModel(
            name='Factp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Facturas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Facturas',
            },
        ),
        migrations.AddField(
            model_name='factdian',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Facturas'),
        ),
        migrations.AddField(
            model_name='factdian',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
