# Generated by Django 2.2.1 on 2022-02-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_auto_20220211_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factp',
            old_name='precio',
            new_name='descuento',
        ),
        migrations.RenameField(
            model_name='factp',
            old_name='total',
            new_name='porc_iva',
        ),
        migrations.AddField(
            model_name='factp',
            name='valor_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='factp',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='factp',
            name='valor_unidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='facturas',
            name='factura',
            field=models.IntegerField(default=0),
        ),
    ]
