# Generated by Django 2.2.1 on 2022-02-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_auto_20220214_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='factp',
            name='codigo_de_barra',
            field=models.CharField(blank=True, default='', help_text='Código de Barra', max_length=100, null=True),
        ),
    ]
