# Generated by Django 2.2.1 on 2022-02-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_factp_codigo_de_barra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factp',
            name='producto',
            field=models.CharField(blank=True, default='', help_text='Nombre del producto', max_length=100, null=True),
        ),
    ]
