# Generated by Django 2.2.1 on 2022-02-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_auto_20220215_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factp',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='factp',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='factp',
            name='valor_unidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
