# Generated by Django 2.2.1 on 2022-02-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_auto_20220227_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='cambio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='facturas',
            name='recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
