# Generated by Django 2.2.1 on 2022-03-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_auto_20220302_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factp',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='factp',
            name='porc_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='factp',
            name='valor_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='factp',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
