# Generated by Django 2.2.1 on 2022-03-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0009_auto_20220302_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormasPagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre Forma de Pago', max_length=100)),
            ],
            options={
                'verbose_name': 'Nombres Formas de Pago',
                'verbose_name_plural': 'Nombre Forma de Pago',
            },
        ),
        migrations.CreateModel(
            name='frm_de_pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Facturas')),
                ('frm_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.FormasPagos')),
            ],
            options={
                'verbose_name': 'Formas de Pago',
                'verbose_name_plural': 'Forma de pago',
            },
        ),
    ]
