# Generated by Django 2.2.1 on 2022-03-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0010_formaspagos_frm_de_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaspagos',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
