# Generated by Django 2.2.1 on 2022-03-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0012_auto_20220303_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='cerrado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
