# Generated by Django 2.2.1 on 2022-03-07 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturas', '0013_facturas_cerrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cierres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('valor_total_registrado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pos_no', models.IntegerField(default=1)),
                ('factura_desde', models.CharField(max_length=15)),
                ('factura_hasta', models.CharField(max_length=15)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierres de Cajas',
                'verbose_name_plural': 'Cierre de Caja',
            },
        ),
        migrations.CreateModel(
            name='Cierres1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('ventas_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ventas_cubcat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ventas_cubcat_excluidas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ventas_cubcat_excentas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ventas_cubcat_grabadas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Cierres')),
            ],
            options={
                'verbose_name': 'DEtalles cierres de caja.',
                'verbose_name_plural': 'Detalle cierre de caja.',
            },
        ),
        migrations.CreateModel(
            name='FormasPagosCierres1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Cierres')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.FormasPagos')),
            ],
            options={
                'verbose_name': 'Formas de Pagos',
                'verbose_name_plural': 'Froma de Pago',
            },
        ),
        migrations.CreateModel(
            name='GrabadosCierres1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('tarifa_iva', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('base_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Cierres')),
            ],
            options={
                'verbose_name': 'IVA grabados',
                'verbose_name_plural': 'IVA grabado',
            },
        ),
        migrations.DeleteModel(
            name='frm_de_pagos',
        ),
    ]
