# Generated by Django 2.2.1 on 2022-03-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0014_auto_20220307_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='con_electronica',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
