# Generated by Django 2.2.1 on 2022-03-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0016_factp_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='vales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
