# Generated by Django 2.2.1 on 2022-03-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0017_facturas_vales'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
