# Generated by Django 2.2.1 on 2022-03-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0019_auto_20220315_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierres1',
            name='base_caja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cierres1',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
