# Generated by Django 2.2.1 on 2022-03-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0020_auto_20220315_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierres',
            name='cierre_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
