# Generated by Django 2.2.1 on 2022-03-18 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturas', '0022_auto_20220316_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('vale_no', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField()),
                ('concepto', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('beneficiario', models.CharField(help_text='Nombre Beneficiario', max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vales de Caja',
                'verbose_name_plural': 'Vale de Caja',
            },
        ),
    ]
