# Generated by Django 2.2.1 on 2022-03-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0023_vales'),
    ]

    operations = [
        migrations.AddField(
            model_name='vales',
            name='anulado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
