# Generated by Django 2.2.1 on 2022-03-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0024_vales_anulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
