# Generated by Django 2.2.1 on 2022-03-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0025_facturas_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='vales',
            name='cerrado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
