# Generated by Django 2.2.1 on 2022-03-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0027_pagosvales'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='saldo_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
