# Generated by Django 2.2.1 on 2022-03-18 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0008_profile_tercero_mostrador'),
        ('facturas', '0028_facturas_saldo_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='tercero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generales.Terceros'),
            preserve_default=False,
        ),
    ]
