# Generated by Django 2.2.1 on 2022-05-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0031_auto_20220329_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cierres1',
            old_name='ventas_cubcat',
            new_name='ventas_subcat',
        ),
        migrations.RenameField(
            model_name='cierres1',
            old_name='ventas_cubcat_excentas',
            new_name='ventas_subcat_excentas',
        ),
        migrations.RenameField(
            model_name='cierres1',
            old_name='ventas_cubcat_excluidas',
            new_name='ventas_subcat_excluidas',
        ),
        migrations.RenameField(
            model_name='cierres1',
            old_name='ventas_cubcat_grabadas',
            new_name='ventas_subcat_grabadas',
        ),
    ]
